spring.application.name=microservicio
spring.datasource.url = jdbc:mysql://localhost:3307/microservicio
spring.datasource.username = root
spring.datasource.password = root

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true

server.port=8080
spring.jpa.open-in-view=false

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=swagger-ui.html


